// Generated by typings
// Source: https://raw.githubusercontent.com/typed-typings/npm-mime/c7c5810698b7eaa421702a53644a8963d372f758/mime.d.ts
declare module '~mime/mime' {
class Mime {
  types: {
    [extension: string]: string;
  }

  extensions: {
    [extension: string]: string;
  }

  define (map: Map): void;
  load (filename: string): void;
  lookup (path: string, fallback?: string): string;
  extension (mimeType: string): string;
}

interface Map {
  [type: string]: string[];
}

var mime: Mime & {
  default_type: string;
  charsets: {
    lookup (mimeType: string, fallback?: string): string;
  }
  Mime: typeof Mime;
}

export = mime;
}
declare module 'mime/mime' {
import alias = require('~mime/mime');
export = alias;
}
declare module 'mime' {
import alias = require('~mime/mime');
export = alias;
}
